upptime/upptime.js.org

docs/get-started.md

The static site should be driven from the `gh-pages` branch (unless I'm mistaken)

docs: Set the publishing source to correct branch

---

docs/configuration.md

The current `yaml` example in the documentation uses `hred`, it should likely be `href`.

Fix Custom CSS sytlesheet syntax `hred` to `href`

---

docs/how-it-works.md

Switched links to examples for viewing commit history and issues so they are associated with the correct section.

Correct example placement in how-it-works.md

---

docs/get-started.md

Settings for `GitHub Pages` has been moved to an independent sub-section. This PR updates the documentation for the same.

📝 github pages section

---

src/css/custom.css
src/pages/styles.module.css

**Resolves ISSUE** [#363 ](https://github.com/upptime/upptime/issues/363)
**Fixes**: _Responsiveness_- button overflow at `x-axis` & image hiding the text.
**Preview after fixes:**

📱 fix home hero buttons and text ui

---

docs/configuration.md

I noticed the documentation for this was missing from the docs.

Add documentation for TCP endpoint checks

---

docs/configuration.md

Hey, I noticed that the [night theme](https://github.com/upptime/status-page/blob/1de42c622b7dbfff66ac20524d7cd6b9e5ffa478/static/themes/night.css) isn't listed in the [configuration page](https://upptime.js.org/docs/configuration/) in the docs so I added it (: 
By the way, I'm also thinking about adding screenshots of each theme so people can see them and choose a theme, what do you think?
Cheers!

Add missing night theme to the docs.

---

docs/triggers.md

fixed url of create a repo dispatch event -- and a note. rest api is think it's changed. I'm trying to figure out what changed in it

fixed url and REST API commnad

---

README.md

They point to `master` while the branches have been renamed to `main`
While GitHub does redirect to the default branch should this still be corrected.

Correct wrong branch in CONTRIBUTING and CoC URLs

---

docs/get-started.md

Some information about creating and applying a PAT are not up to date.
For example do PATs now have an expiration dropdown that needs to be changed (Unless you want to recreate the PAT every X days) and `Secrets` in the Repository Settings now reveals a collection of other settings to choose from.

Fix outdated info about PAT creation

---

docs/scheduled-maintenance.md

Pretty sure I'm not the only one who got confused with `.220Z`.
There is really no need to use milliseconds. Instead, should the examples include a valid timezone definition (`+00:00` in this case) to show a proper timestamp format with an off-set time.

Give better ISO timestamp example

---

docs/configuration.md

Add documentation for `__dangerous__body_down_if_text_missing` and `__dangerous__body_degraded_if_text_missing` features.

Add missing documentation

---

docs/configuration.md

Upptime should inform the user about the limit of how frequently a scheduled action can run.

Add note about max frequency in schedules

---

.github/workflows/node.yml

Current GitHub Pages deploy action fails. And action repository ([maxheld83/ghpages](https://github.com/maxheld83/ghpages)) looks like not maintained anymore.
I changed [maxheld83/ghpages](https://github.com/maxheld83/ghpages) with [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages).
Failed action: https://github.com/upptime/upptime.js.org/actions/runs/3107099481/jobs/5034796351
Successfull action: https://github.com/sercanuste/upptime.js.org/actions/runs/3111255468/jobs/5043326077

💚 Change GitHub Pages deploy action

---

docs/triggers.md

I finally got the API to work. It looks like a lot has changed since this was originally written. Obtaining a fine-grained PAT an the `curl` command updates work for me.
Also I changed the example to trigger the `uptime.yml` workflow as that is likely to be one that people will want to trigger remotely from a real cron. I wasn't able to get `https://api.github.com/repos/{YOUR GITHUB USERNAME}/{YOUR UPPTIME REPO NAME}/actions/workflows/uptime/dispatches` to work. It always reports:
```json
{
"message": "Not Found",
"documentation_url": "https://docs.github.com/rest/reference/actions#create-a-workflow-dispatch-event"
}
```
From the documentation linked above, the filename can be replaced with the *workflow_id* which is obtained from  the `.../actions/workflows` endpoint.
I can't test the …

Update Using GitHub API section of triggers.md to current API

---

docs/packages.md

The link to [`@upptime/status-page`](https://www.npmjs.com/package/@upptime/status-page) in [`docs/packages`](https://upptime.js.org/docs/packages) currently points to [`@upptime/graphs`](https://www.npmjs.com/package/@upptime/graphs)
PS:- Thanks for making and maintaining this awesome project :heart:

fix link to npmjs for status-page

---

docs/get-started.md

GitHub have shifted a few things around, renamed some labels and controls and they've also introduced a new PAT type and the original PATs are now called legacy. They differ in how permissions (scopes) for the tokens are handled. I've updated the document to describe the process for the modern PATs.
If there's interest I can edit the section to highlight how to do it for both Legacy and modern PATs. I am not doing it right away though as it is probably better to guide users to use the new PATs anyway.

Update the Get Started document to reflect changes in the GitHub web UI

---

docs/get-started.md

The CI still passes when updating .upptimerc.yml without the Workflows permission set but it prevents some data from being updated (the README and websites being tracked).
Example without Workflows permission:

Add missing required token permission (Workflows)

---

docs/get-started.md

Close https://github.com/upptime/upptime/issues/797
- Add Issues permission requirement in setup steps.
- Update the summary paragraph to make permission requirements consistent.

fix(docs): require read-write permission of Issues for PAT

---

docs/configuration.md

Per <https://github.com/upptime/uptime-monitor/pull/231#issuecomment-1849047884> request by @AnandChowdhary.

docs: added `ipv6: true` example

---

docs/notifications.md

Added information on configuring custom notifications

Added documentation for custom notifications

---

docs/configuration.md
docs/how-it-works.md

This PR adds documentation on how to prevent uptime from deleting issues. 
The deletion of issues by uptime might get you by surprise, as it can be seen at https://github.com/upptime/upptime/issues/917
It turns out, it is a "feature and not a bug" :) 
See some additional context on this feature: https://github.com/upptime/upptime/discussions/492#discussioncomment-8179339
This PR includes:

docs: document skip delete issues feature

---

docs/configuration.md

Adds documentation for the existing `delay` parameter. Ref: https://github.com/upptime/upptime/issues/625#issuecomment-1407608205

docs(configuration): add missing delay option documentation

---

docs/configuration.md

Hey there! I noticed it took me a while to figure out how to set the userContentBaseUrl option in the Upptime configuration, so I thought I'd add a quick note in the docs to help others out. By default, it's https://raw.githubusercontent.com, but you can change it if you need to use a custom URL. I've added a brief explanation and example to make it easier to find. Hope this helps!

Add Documentation for userContentBaseUrl Configuration in Upptime configuration.md

---

docs/configuration.md

This feature (custom slug for site) has been implemented in code, but missing in document. Mentioning this may save some time for others with similar requirements.

Mention site slug option in document

---

docs/notifications.md

Gotify was added in PR #[256](https://github.com/upptime/uptime-monitor/pull/256) of [upptime/uptime-monitor](https://github.com/upptime/uptime-monitor) repo as notification option 🚀 
This PR updates Notifications documentation related to Gotify.

Add Gotify to notifications documentation

---

docs/get-started.md

The documentation references the branch `gh-pages` later on, but GitHub does not include all branches by default when creating new repository from template. I've updated the documentation to include that you should check the `Include all branches` checkbox.
Image:

Update get-started.md with information about including all branches
